ALTER TABLE teamsGW1 ADD deductions INT DEFAULT 0 AFTER liveOP, ADD transfers INT DEFAULT 0 AFTER liveOP, ADD benchScore INT DEFAULT 0 AFTER liveOP;
ALTER TABLE teamsGW2 ADD deductions INT DEFAULT 0 AFTER liveOP, ADD transfers INT DEFAULT 0 AFTER liveOP, ADD benchScore INT DEFAULT 0 AFTER liveOP;
ALTER TABLE teamsGW3 ADD deductions INT DEFAULT 0 AFTER liveOP, ADD transfers INT DEFAULT 0 AFTER liveOP, ADD benchScore INT DEFAULT 0 AFTER liveOP;
ALTER TABLE teamsGW4 ADD deductions INT DEFAULT 0 AFTER liveOP, ADD transfers INT DEFAULT 0 AFTER liveOP, ADD benchScore INT DEFAULT 0 AFTER liveOP;
ALTER TABLE teamsGW5 ADD deductions INT DEFAULT 0 AFTER liveOP, ADD transfers INT DEFAULT 0 AFTER liveOP, ADD benchScore INT DEFAULT 0 AFTER liveOP;
ALTER TABLE teamsGW6 ADD deductions INT DEFAULT 0 AFTER liveOP, ADD transfers INT DEFAULT 0 AFTER liveOP, ADD benchScore INT DEFAULT 0 AFTER liveOP;
ALTER TABLE teamsGW7 ADD deductions INT DEFAULT 0 AFTER liveOP, ADD transfers INT DEFAULT 0 AFTER liveOP, ADD benchScore INT DEFAULT 0 AFTER liveOP;
ALTER TABLE teamsGW8 ADD deductions INT DEFAULT 0 AFTER liveOP, ADD transfers INT DEFAULT 0 AFTER liveOP, ADD benchScore INT DEFAULT 0 AFTER liveOP;